---
  extends: "eslint:recommended"
  rules:
    # Error catching rules
    no-unsafe-negation: "error"
    # Best practice rule errors
    curly: "error"
    default-case: "error"
    dot-location:
      - "error"
      - "property"
    dot-notation: "error"
    eqeqeq: "error"
    no-caller: "error"
    no-else-return: "error"
    no-empty-function: "error"
    no-eq-null: "error"
    no-extra-bind: "error"
    no-floating-decimal: "error"
    no-global-assign: "error"
    no-implicit-coercion: "error"
    no-implicit-globals: "error"
    no-implied-eval: "error"
    no-iterator: "error"
    no-lone-blocks: "error"
    no-multi-spaces: "error"
    no-new-func: "error"
    no-new-wrappers: "error"
    no-octal-escape: "error"
    no-param-reassign: "error"
    no-proto: "error"
    no-return-assign:
      - "error"
      - "always"
    no-self-assign: "error"
    no-self-compare: "error"
    no-sequences: "error"
    no-throw-literal: "error"
    no-useless-call: "error"
    no-useless-concat: "error"
    no-useless-escape: "error"
    no-with: "error"
    radix:
      - "error"
      - "as-needed"
    # Strict mode rules
    strict: "error"
    # Variable rule errors
    no-shadow-restricted-names: "error"
    no-use-before-define: "error"
    # Stylistic errors (may be covered by JSCS as well)
    array-bracket-spacing: "error"
    block-spacing: "error"
    brace-style: "error"
    comma-dangle: "error"
    comma-spacing: "error"
    comma-style: "error"
    computed-property-spacing: "error"
    func-call-spacing: "error"
    indent: 
      - "error"
      - 4
    key-spacing: "error"
    line-comment-position: "error"
    new-parens: "error"
    no-inline-comments: "error"
    no-tabs: "error"
    no-trailing-spaces: "error"
    no-whitespace-before-property: "error"
    object-curly-newline:
      - "error"
      - ObjectExpression:
          minProperties: 1
    quotes:
      - "error"
      - "single"
      - avoidEscape: true
        allowTemplateLiterals: true
    semi: "error"
    # Warnings
    no-template-curly-in-string: 1
    # Style rules ported from jscs
    keyword-spacing: "error"
    space-before-blocks: "error"
    arrow-spacing: "error"
    wrap-iife:
      - "error"
      - "inside"
    space-before-function-paren: "error"
    one-var:
      - "error"
      - "never"
    no-empty:
      - "error"
      - allowEmptyCatch: true
    quote-props:
      - "error"
      - "as-needed"
    operator-linebreak:
      - "error"
      - "after"
    space-unary-ops:
      - "error"
      - words: true
        nonwords: false
    space-infix-ops: "error"
    camelcase: "error"
    no-multi-str: "error"
    no-multiple-empty-lines: 
      - "error"
      - max: 1
        maxEOF: 1
    no-mixed-spaces-and-tabs: "error"
    eol-last: "error"
    yoda: "error"
    spaced-comment: "error"
    func-style: "error"
    semi-spacing: "error"
    new-cap: "error"
